Adding random failures

diff --git a/.cloudbees/workflows/another-workflow.yaml b/.cloudbees/workflows/another-workflow.yaml
--- a/.cloudbees/workflows/another-workflow.yaml
+++ b/.cloudbees/workflows/another-workflow.yaml
@@ -28,6 +28,11 @@ jobs:
     - name: Dummy wait
       uses: docker://alpine:3.20.2
       run: |
+        FAIL=$(shuf -i 1-3 -n 1)
+        if (($FAIL == 3)); then
+          echo "Failing the job..."
+          exit 1
+        fi
         echo "Waiting for 10 seconds..."
         sleep 10
 
